MONITORING_WINDOW_SECONDS = 10
MONITORING_STEP_SECONDS = 2

EPISODE_START_THRESHOLD = 0.55
EPISODE_END_THRESHOLD = 0.40

MIN_EPISODE_DURATION_SECONDS = 4
MAX_EPISODE_GAP_SECONDS = 6

MIN_CONFIDENCE_FOR_EPISODE = 0.50
MIN_DATA_QUALITY_FOR_EPISODE = 0.50
